language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '8'
script:
  - npm start
  - npm test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
