language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '10'
script:
  - npm start
  - $(npm bin)/print-env TRAVIS
  - npm test
  - npm run demo
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
